var acc3 = [["-Lvl1","HOME",""],
["My Assignments","",""],
["Project Status","",""],
["Project Pools","",""],
["Checked out files","",""],
["Client and Contact Notes Aasigned to Me","",""],
["Entity file lookup","",""],
["File discussion","",""],
["Notifications","",""],
["Project Assignment","",""],
["Recently accessed files","",""],
["Reports","",""],
["Return and Project Notes","",""],
["Staff Productivity KPI","",""],
["Task Assignment","",""],
["Transaction Summary","",""],
["-Lvl1","TIME CAPTURE",""],
["Clocks","",""],
["-Lvl2","Time Transactions",""],
["Daily Entry","",""],
["Unreleased Transactions","",""],
["Ready to Post","",""],
["Ready for Review","",""],
["Posted Transactions","",""],
["-Lvl1","TAX",""],
["New return","",""],
["Return Manager","",""],
["Batch Manager","",""],
["Electronic Filing Status","",""],
["Tax Notebook Toolkit","",""],
["My1040Data Toolkit","",""],
["-Lvl2","Configuration",""],
["Return configuration sets","",""],
["Return print sets","",""],
["Organizer print sets","",""],
["Correspondence Manager","",""],
["-Lvl1","DOCUMENT",""],
["Add file","",""],
["-Lvl2", "Search for files", ""],
["-Lvl3","Saved Searches",""],
["My searches","",""],
["-Lvl3","Organize results",""],
["Sort by","",""],
["Group by","",""],
["-Lvl3","File Groups",""],
["Public file groups","",""],
["Advanced Search","",""],
["-Lvl2","Files", "", ""],
["File list","",""],
["Recent files","",""],
["Recent entities","",""],
["File groups","",""],
["Checked out files","",""],
["Incoming files","",""],
["Share Safe","",""],
["Task assignments","",""],
["-Lvl1", "ACCOUNTS RECEIVABLE", ""],
["AR transactions","",""],
["Calculate finance charges","",""],
["Print statements","",""],
["-Lvl1","REPORTS",""],
["Reports Manager","",""],
["Document reports","",""],
["Portal reports","",""],
["Print labels","",""],
["-Lvl1","ADMINISTRATION",""],
["AR corrections","",""],
["WIP corrections/transfers","",""],
["Recalculate WIP/TE amounts","",""],
["Set the reconciliation date","",""],
["Year-end procedures","",""],
["-Lvl1","WORKSTREAM",""],
["-Lvl2","Projects","Landing page"],
["-Lvl2","Configuration...",""],
["Project Types","","Type ID, Type Name, Primary Service Type"],
["Project Templates","","Template ID, Template Name, Primary Service Type, Template Status"],
["Project Pools","",""],
["-Lvl1","BILLING & INVOICING",""],
["Bill WIP","",""],
["Invoices","",""],
["-Lvl1","CLIENTS",""],
["Client Manager","","Client ID, Client Sub-ID, Client Sort Name, Client Sub-Description, Primary Client, Office, Business unit, Line of business, Client Type, Status, Class, Year End (Example: 12/31)"],
["Non-client Manager","",""],
["-Lvl1","STAFF",""],
["Staff","","Staff Manager: Home Office, Report Name, Reporting Manager, Staff ID, Status, System Email"],
["-Lvl1","FIRM",""],
["-Lvl2","Firm Settings and Defaults",""],
["General","","General Information, Addresses, Phone numbers, Country/Region"],
["Email Settings","","Email discousure/Confidentiality note"],
["-Lvl3","","Setting Defaults"],
["Client and staff","","Section, Identify clients, phone mask, phone extensions"],
["Sticky notes","","Section, Enable private sticky notes"],
["-Lvl4","Organizational Units",""],
["Office","",""],
["Business Units","",""],
["Regions","",""],
["-Lvl4","Practice",""],
["Accounts Receivable Settings","","AR Settings"],
["Billing Error Conditions","","Billing Defaults"],
["Billing Settings","","Billing Defaults"],
["Holiday Planner","","Holidays"],
["Other Practice Settings","",""],
["Time Capture Settings","","TC Settings"],
["Time Capture Error Conditions","","TC Error Conditions"],
["-Lvl5","Notification Setup",""],
["Accounts Receivable Notifications","","AR Notifications"],
["Billing Notifications","","Billing Notifications"],
["Time Capture","","Time Capture Notifications"],
["-Lvl5","Login Setup",""],
["Login mode/Authentication mode","",""],
["Session timeout configuration","",""],
["Password Configuration","",""],
["Federation Services Settings","",""],
["-Lvl2","Lists",""],
["-Lvl3","Client Lists",""],
["Client Associate Types","",""],
["Client Responsible Staff","",""],
["Client Types","",""],
["Contact Categories","",""],
["Custom Fields - Client Associates","",""],
["Custom Fields - Client Contacts","",""],
["Custom Fields - Clients","",""],
["Identification Number Type","",""],
["Lines of Business","",""],
["Marketing Method","","Direct mail, Email campaign, Facebook, Google"],
["Primary Service Types","","Accounting Services, Audit Services, Consulting Services, Tax Services"],
["-Lvl3", "Document Lists", ""],
["Disallowed File Types","",""],
["Document types","",""],
["Portal Announcements","",""],
["Years","",""],
["-Lvl3", "General Lists", ""],
["Notes Categories","",""],
["-Lvl3", "Non-client Lists", ""],
["Identification Number Type","",""],
["Non-client Type","",""],
["-Lvl3", "Practice Lists", ""],
["Bank Accounts","",""],
["Bill Manager","",""],
["Bill Rates","",""],
["Billing Fee Agreements","","BFA"],
["CPE Categories","",""],
["CPE Types","",""],
["Custom Fields - Time Entry","",""],
["Finance Charges","",""],
["Invoice Status","",""],
["Reasons","",""],
["Service Code Classes","",""],
["-Lvl4","Service Codes",""],
["Category","",""],
["Service Codes","",""],
["Subcategory","",""],
["-Lvl4","Tax Rates",""],
["-Lvl4","Work Locations",""],
["-Lvl2","Staff Lists",""],
["-Lvl3","AoE","","Area of Experience"],
["Area of Expertise","","AoE"],
["Area of Expertise Levels","","AoE Levels"],
["Custom Fields - Staff","",""],
["Departments","",""],
["Positions", "", ""],
["-Lvl2","Tax Lists",""],
["Return Groups","",""],
["Signer Locations","",""],
["-Lvl2","Workstream List",""],
["Complexities","",""],
["Custom Fields ","",""],
["Delivery Methods","",""],
["Form Due Dates","",""],
["Milestone Dates","",""],
["Priorities","",""],
["Status","",""],
["-Lvl2","Notifications","Condition, Message, Priority, Select By, Recipient(s), Recipients, Staff"],
["Invoice and statement templates - not implemented","",""],
["Utilities - not implemented","",""],
["-Lvl2","Invoice and statement templates",""],
["-Lvl2","Utilities",""],
["-Lvl3","Common Utilities",""],
["Batch link clients","Associate client across applications and make it easier to share information between different systems.",""],
["Convert tax date from a previous vendor","Upload returns created with third party tax software for conversion to Wolters Kluwer software.",""],
["Create a client list for Portal","Use the list to make it easier to send files to a client portal.",""],
["Create a computer snapshot","Capture system date to send to SUpport.",""],
["Export installation statistics","Get data about computers using Install and Update Manager.",""],
["Import clients","Create clients using information in a file.",""],
["Import staff","Create staff using information in a file.",""],
["Migrate data","Copy data from the CCH ProSystem fx Suite.",""],
["Send new user instructions","Select users created by data migration, import, or active directory that need installation and login instructions.",""],
["-Lvl3","Document Utilities",""],
["File GUID Translatior","Cross reference your GUID to a file name or file name to GUID.",""],
["File Export","Export files from document",""],
["-Lvl3","Practice Utilities",""],
["Extract Practice Records","Extract Practice records to send to support",""],
["-Lvl3","Support Utilities",""],
["Retrieve Tax Return GUID","Retrieve Return GUID",""],
["Restore Deleted Returns","Restore deleted tax returns",""],
["Reset SSO Password","Reset user's SSO password",""],
["CCO Axcess Email Filter Utility","Email Whitelist in CCH Axcess SUite.",""],
["-Lvl3","Workstream Utilities",""],
["Extract Workstream Records","Extract Workstream Records to send to support",""],
["Batch link CCH Axcess Tax Returns","Select CCH Axcess Tax returns to link to projects",""],
["-Lvl1","SECURITY",""],
["Licensing and product access","",""],
["Security groups","",""],
["Access groups","",""],
["Roles","",""],
["-Lvl1","Feedback Forum",""],
["-Lvl1","CCH Software News",""],
];				
