//ShortName:Long name Description:
var acc3 = [["-Lvl1", "Canada", ""],
["-Lvl2", "British Columbia", ""],
["Van", "Vancouver", "1 airport"],
["-Lvl2", "Ontario", ""],
["Tor", "Toronto", "large|1 airport"],
["-Lvl2", "Quebec", ""],
["Mon", "Montreal", "large|1 airport"],
["-Lvl1", "United States", ""],
["-Lvl2", "Texas", ""],
["Aus", "Austin", "large|1 airport"],
["Hou", "Houston", "large|2 airports"],
["Dal", "Dallas", "large|2 airports"],
["Par", "Paris", ""],
["Ath", "Athens", ""],
["It", "Italy", ""],
["Dub", "Dublin", ""],
["FW", "Fort Worth", "large"],
["SAnt", "San Antonio", "large|1 airport"],
["SAng", "San Angelo", ""],
["TA", "Texarkana, TX", ""],
["-Lvl3", "Irving", ""],
["BL", "Beltline, Irving", ""],
["-Lvl2", "New Mexico", ""],
["Alb", "Albuquerque", "1 airport"],
["SFe", "Santa Fe", "1 airport"],
["Taos", "Taos", ""],
["-Lvl2", "Oklahoma", ""],
["OKC", "Oklahoma City", "1 airport"],
["Tul", "Tulsa", "1 airport"],
["Dun", "Duncan", ""],
["-Lvl2", "Arkansas", ""],
["TAA", "Texarkana, AK", ""],
["LR", "Little Rock", "1 airport"],
["-Lvl2", "Louisiana", ""],
["NO", "New Orleans", "large|1 airport"],
["Sl", "Slidell", ""],
["BR", "Baton Rouge", ""],
["Sh", "Shreveport", ""],
["-Lvl2", "Kansas", ""],
["WICH", "Wichita", ""],
["Top", "Topeka", ""],
["KSK", "Kansas City, KS", "1 airport"],
["-Lvl2", "Colorado", ""],
["DEN", "Denver", "large|1 airport"],
["BO", "Boulder", ""],
["-Lvl2", "Illinois", ""],
["","Abingdon","City|3,319","Knox"],
["","Addieville","Village|252","Knox"],
["","Addison","Village|36,942","DuPage"],
["","Adeline","Village|85","Ogle"],
["","Albany","Village|891","Whiteside"],
["","Albers","Village|1190","Clinton"],
["","Albion","City|1,988","Edwards"],
["","Aledo","City|3,640","Mercer"],
["","Alexis","Village|831","Warren"],
["","Algonquin","Village|30,046","Kane"],
["","Alhambra","Village|681","Madison"],
["","Allendale","Village|475","Wabash"],
["","Allenville","Village|148","Moultrie"],
["","Allerton","Village|291","Vermilion"],
["","Alma","Village|320","Marion"],
["","Alorton","Village|2,002","St. Clair"],
["","Alpha","Village|671","Henry"],
["","Alsey","Village|227","Scott"],
["","Alsip","Village|19,277","Cook"],
["","Altamont","City|2,319","Effingham"],
["","Alto Pass","Village|391","Union"],
["","Alton","City|27,865","Madison"],
["","Altona","Village|531","Knox"],
["","Alvan","Village|270","Vermilion"],
["","Amboy","City|2,500","Lee"],
["","Anchor","Village|146","McLean"],
["","Andalusia","Village|1,178","Rock Island"],
["","Andover","Village|578","Henry"],
["","Anna","City|4,442","Union"],
["","Annawan","Town","878","Henry"],
["","Antioch","Village|14,430","Lake"],
["","Apple River","Village|366","Jo Daviess"],
["","Arcola","City|2,916","Douglas"],
["","Arenzville","Village|409","Cass"],
["","Argenta","Village|947","Macon"],
["","Arlington","Village|193","Bureau"],
["","Arlington Heights","Village|75,101","Cook"],
["","Armington","Village|343","Tazewell"],
["","Aroma Park","Village|743","Kankakee"],
["","Arrowsmith","Village|294","McLean"],
["","Arthur","Village|2,288","Douglas"],
["","Ashkum","Village|761","Iroquois"],
["","Ashland","Village|1,333","Cass"],
["","Ashley","City|536","Washington"],
["","Ashmore","Village|785","Coles"],
["","Assumption","City|1,168","Christian"],
["","Astoria","Town","1,141","Fulton"],
["","Athens","City|1,988","Menard"],
["","Atkinson","Town","972","Henry"],
["","Atlanta","City|1,692","Logan"],
["","Atwood","Village|1,224","Douglas"],
["","Auburn","City|4,771","Sangamon"],
["","Augusta","Village|587","Hancock"],
["","Aurora","City|197,899","DuPage"],
["","Ava","City|654","Jackson"],
["","Aviston","Village|1,945","Clinton"],
["","Avon","Village|799","Fulton"],
["","Baldwin","Village|373","Randolph"],
["","Banner","Village|189","Fulton"],
["","Bannockburn","Village|1,583","Lake"],
["","Bardolph","Village|251","McDonough"],
["","Barrington","Village|10,327","Cook"],
["","Barrington Hills","Village|4,209","Cook"],
["","Barry","City|1,318","Pike"],
["","Bartelso","Village|595","Clinton"],
["","Bartlett","Village|41,208","Cook"],
["","Bartonville","Village|6,471","Peoria"],
["","Basco","Village|98","Hancock"],
["","Batavia","City|26,045","DuPage"],
["","Batchtown","Village|214","Calhoun"],
["","Bath","Village|333","Mason"],
["","Bay View Gardens","Village|378","Woodford"],
["","Baylis","Village|205","Pike"],
["","Beach Park","Village|13,638","Lake"],
["","Beardstown","City|6,123","Cass"],
["","Beaverville","Village|362","Iroquois"],
["","Beckemeyer","Village|1,040","Clinton"],
["","Bedford Park","Village|580","Cook"],
["","Beecher","Village|4,359","Will"],
["","Beecher City","Village|463","Effingham"],
["","Belgium","Village|404","Vermilion"],
["","Belknap","Village|104","Johnson"],
["","Belle Prairie City","Town","54","Hamilton"],
["","Belle Rive","Village|361","Jefferson"],
["","Belleville","City|44,478","St. Clair"],
["","Bellevue","Village|1,978","Peoria"],
["","Bellflower","Village|357","McLean"],
["","Bellmont","Village|276","Wabash"],
["","Bellwood","Village|19,071","Cook"],
["","Belvidere","City|25,585","Boone"],
["","Bement","Village|1,730","Piatt"],
["","Benld","City|1,556","Macoupin"],
["","Bensenville","Village|18,352","DuPage"],
["","Benson","Village|423","Woodford"],
["","Bentley","Town","35","Hancock"],
["","Benton","City|7,087","Franklin"],
["","Berkeley","Village|5,209","Cook"],
["","Berlin","Village|180","Sangamon"],
["","Berwyn","City|56,657","Cook"],
["","Bethalto","Village|9,521","Madison"],
["","Bethany","Village|1,352","Moultrie"],
["","Big Rock","Village|1,126","Kane"],
["","Biggsville","Village|304","Henderson"],
["","Bingham","Village|83","Fayette"],
["","Bishop Hill","Village|128","Henry"],
["","Bismarck","Village|579","Vermilion"],
["","Blandinsville","Village|651","McDonough"],
["","Bloomingdale","Village|22,018","DuPage"],
["","Bloomington","City|76,610","McLean"],
["","Blue Island","City|23,706","Cook"],
["","Blue Mound","Village|1,158","Macon"],
["","Bluffs","Village|715","Scott"],
["","Bluford","Village|688","Jefferson"],
["","Bolingbrook","Village|73,366","DuPage"],
["","Bondville","Village|443","Champaign"],
["","Bone Gap","Village|246","Edwards"],
["","Bonfield","Village|382","Kankakee"],
["","Bonnie","Village|397","Jefferson"],
["","Bourbonnais","Village|18,631","Kankakee"],
["","Bowen","Village|494","Hancock"],
["","Braceville","Village|793","Grundy"],
["","Bradford","Village|768","Stark"],
["","Bradley","Village|15,895","Kankakee"],
["","Braidwood","City|6,191","Will"],
["","Breese","City|4,442","Clinton"],
["","Bridgeport","City|1,886","Lawrence"],
["","Bridgeview","Village|16,446","Cook"],
["","Brighton","Village|2,254","Macoupin"],
["","Brimfield","Village|868","Peoria"],
["","Broadlands","Village|349","Champaign"],
["","Broadview","Village|7,932","Cook"],
["","Broadwell","Village|145","Logan"],
["","Brocton","Village|322","Edgar"],
["","Brookfield","Village|18,978","Cook"],
["","Brooklyn","Village|749","St. Clair"],
["","Brookport","City|984","Massac"],
["","Broughton","Village|194","Hamilton"],
["","Browning","Village|137","Schuyler"],
["","Browns","Village|134","Edwards"],
["","Brownstown","Village|759","Fayette"],
["","Brussels","Village|141","Calhoun"],
["","Bryant","Village|220","Fulton"],
["","Buckingham","Village|300","Kankakee"],
["","Buckley","Village|600","Iroquois"],
["","Buckner","Village|462","Franklin"],
["","Buda","Village|538","Bureau"],
["","Buffalo","Village|503","Sangamon"],
["","Buffalo Grove","Village|41,496","Cook"],
["","Bull Valley","Village|1,077","McHenry"],
["","Bulpitt","Village|222","Christian"],
["","Buncombe","Village|203","Johnson"],
["","Bunker Hill","City|1,774","Macoupin"],
["","Burbank","City|28,925","Cook"],
["","Bureau Junction","Village|322","Bureau"],
["","Burlington","Village|618","Kane"],
["","Burnham","Village|4,206","Cook"],
["","Burnt Prairie","Village|52","White"],
["","Burr Ridge","Village|10,559","DuPage"],
["","Bush","Village|275","Williamson"],
["","Bushnell","City|3,117","McDonough"],
["","Butler","Village|180","Montgomery"],
["","Byron","City|3,753","Ogle"],
["","Cabery","Village|266","Ford"],
["","Cahokia","Village|15,241","St. Clair"],
["","Cairo","City|2,831","Alexander"],
["","Caledonia","Village|197","Boone"],
["","Calhoun","Village|172","Richland"],
["","Calumet City","City|37,042","Cook"],
["","Calumet Park","Village|7,835","Cook"],
["","Camargo","Village|445","Douglas"],
["","Cambria","Village|1,228","Williamson"],
["","Cambridge","Village|2,160","Henry"],
["","Camden","Village|86","Schuyler"],
["","Camp Point","Village|1,132","Adams"],
["","Campbell Hill","Village|336","Jackson"],
["","Campton Hills","Village|11,131","Kane"],
["","Campus","Village|166","Livingston"],
["","Canton","City|14,704","Fulton"],
["","Cantrall","Village|139","Sangamon"],
["","Capron","Village|1,376","Boone"],
["","Carbon Cliff","Village|2,134","Rock Island"],
["","Carbon Hill","Village|345","Grundy"],
["","Carbondale","City|25,902","Jackson"],
["","Carlinville","City|5,917","Macoupin"],
["","Carlock","Village|552","McLean"],
["","Carlyle","City|3,281","Clinton"],
["","Carmi","City|5,240","White"],
["","Carol Stream","Village|39,711","DuPage"],
["","Carpentersville","Village|37,691","Kane"],
["","Carrier Mills","Village|1,653","Saline"],
["","Carrollton","City|2,484","Greene"],
["","Carterville","City|5,496","Williamson"],
["","Carthage","City|2,605","Hancock"],
["","Cary","Village|18,271","McHenry"],
["","Casey","City|2,769","Clark"],
["","Caseyville","Village|4,245","St. Clair"],
["","Catlin","Village|2,040","Vermilion"],
["","Cave-In-Rock","Village|318","Hardin"],
["","Cedar Point","Village|277","LaSalle"],
["","Cedarville","Village|741","Stephenson"],
["","Central City","Village|1,172","Marion"],
["","Centralia","City|13,032","Clinton"],
["","Centreville","City|5,309","St. Clair"],
["","Cerro Gordo","Village|1,403","Piatt"],
["","Chadwick","Village|551","Carroll"],
["","Champaign","City|81,055","Champaign"],
["","Charleston","City|21,838","Coles"],
["","Chandlerville","Village|553","Cass"],
["","Channahon","Village|12,560","Will"],
["","Chapin","Village|512","Morgan"],
["","Chatham","Village|11,500","Sangamon"],
["","Chatsworth","Town","1,205","Livingston"],
["","Chebanse","Village|1,062","Iroquois"],
["","Chenoa","City|1,785","McLean"],
["","Cherry","Village|482","Bureau"],
["","Cherry Valley","Village|3,162","Winnebago"],
["","Chester","City|8,586","Randolph"],
["","Chesterfield","Village|188","Macoupin"],
["","Chicago","City|2 airports|large|2,695,598","Cook"],
["","Chicago Heights","City|30,276","Cook"],
["","Chicago Ridge","Village|14,305","Cook"],
["","Chillicothe","City|6,097","Peoria"],
["","Chrisman","City|1,343","Edgar"],
["","Christopher","City|2,382","Franklin"],
["","Cicero","Town","83,891","Cook"],
["","Cisco","Village|261","Piatt"],
["","Cisne","Village|672","Wayne"],
["","Cissna Park","Village|846","Iroquois"],
["","Claremont","Village|176","Richland"],
["","Clarendon Hills","Village|8,427","DuPage"],
["","Clay City","Village|959","Clay"],
["","Clayton","Village|709","Adams"],
["","Clear Lake","Village|229","Sangamon"],
["","Cleveland","Village|188","Henry"],
["","Clifton","Village|1,468","Iroquois"],
["","Clinton","City|7,225","DeWitt"],
["","Coal City","Village|5,587","Grundy"],
["","Coal Valley","Village|3,743","Henry"],
["","Coalton","Village|304","Montgomery"],
["","Coatsburg","Village|147","Adams"],
["","Cobden","Village|1,157","Union"],
["","Coffeen","City|685","Montgomery"],
["","Colchester","City|1,401","McDonough"],
["","Coleta","Village|164","Whiteside"],
["","Colfax","Village|1,061","McLean"],
["","Collinsville","City|25,579","Madison"],
["","Colona","City|5,099","Henry"],
["","Colp","Village|225","Williamson"],
["","Columbia","City|9,707","Monroe"],
["","Columbus","Village|99","Adams"],
["","Compton","Village|303","Lee"],
["","Concord","Village|167","Morgan"],
["","Congerville","Village|474","Woodford"],
["","Cooksville","Village|182","McLean"],
["","Cordova","Village|672","Rock Island"],
["","Cornell","Village|467","Livingston"],
["","Cortland","Town","4,270","DeKalb"],
["","Coulterville","Village|945","Randolph"],
["","Country Club Hills","City|16,541","Cook"],
["","Countryside","City|5,895","Cook"],
["","Cowden","Village|629","Shelby"],
["","Crainville","Village|1,254","Williamson"],
["","Creal Springs","City|543","Williamson"],
["","Crescent City","Village|615","Iroquois"],
["","Crest Hill","City|20,837","Will"],
["","Creston","Village|662","Ogle"],
["","Crestwood","Village|10,950","Cook"],
["","Crete","Village|8,259","Will"],
["","Creve Coeur","Village|5,451","Tazewell"],
["","Crossville","Village|745","White"],
["","Crystal Lake","City|40,743","McHenry"],
["","Cuba","City|1,294","Fulton"],
["","Cullom","Village|555","Livingston"],
["","Curran","Village|212","Sangamon"],
["","Cutler","Village|441","Perry"],
["","Cypress","Village|234","Johnson"],
["","Dahlgren","Village|525","Hamilton"],
["","Dakota","Town","506","Stephenson"],
["","Dallas City","City|945","Hancock"],
["","Dalton City","Village|544","Moultrie"],
["","Dalzell","Village|717","Bureau"],
["","Damiansville","Village|491","Clinton"],
["","Dana","Village|159","LaSalle"],
["","Danforth","Village|604","Iroquois"],
["","Danvers","Village|1,154","McLean"],
["","Danville","City|33,027","Vermilion"],
["","Darien","City|22,086","DuPage"],
["","Davis","Village|677","Stephenson"],
["","Davis Junction","Village|2,373","Ogle"],
["","Dawson","Village|509","Sangamon"],
["","DeKalb","City|43,862","DeKalb"],
["","De Land","Village|446","Piatt"],
["","De Pue","Village|1,838","Bureau"],
["","De Soto","Village|1,590","Jackson"],
["","Decatur","City|76,122","Macon"],
["","Deer Creek","Village|704","Tazewell"],
["","Deer Grove","Village|48","Whiteside"],
["","Deer Park","Village|3,200","Cook"],
["","Deerfield","Village|18,225","Cook"],
["","Delavan","City|1,689","Tazewell"],
["","Des Plaines","City|58,364","Cook"],
["","Detroit","Village|83","Pike"],
["","DeWitt","Village|184","DeWitt"],
["","Diamond","Village|2,527","Grundy"],
["","Dieterich","Village|617","Effingham"],
["","Divernon","Village|1,172","Sangamon"],
["","Dix","Village|461","Jefferson"],
["","Dixmoor","Village|3,644","Cook"],
["","Dixon","City|15,733","Lee"],
["","Dolton","Village|23,153","Cook"],
["","Dongola","Village|726","Union"],
["","Donnellson","Village|210","Bond"],
["","Donovan","Village|304","Iroquois"],
["","Dorchester","Village|151","Macoupin"],
["","Dover","Village|168","Bureau"],
["","Dowell","Village|408","Jackson"],
["","Downers Grove","Village|47,833","DuPage"],
["","Downs","Village|1,005","McLean"],
["","Du Bois","Village|205","Washington"],
["","Du Quoin","City|6,109","Perry"],
["","Dunfermline","Village|300","Fulton"],
["","Dunlap","Village|1,386","Peoria"],
["","Dupo","Village|4,138","St. Clair"],
["","Durand","Village|1,443","Winnebago"],
["","Dwight","Village|4,260","Grundy"],
["","Eagarville","Village|127","Macoupin"],
["","Earlville","City|1,701","LaSalle"],
["","East Alton","Village|6,301","Madison"],
["","East Brooklyn","Village|106","Grundy"],
["","East Cape Girardeau","Village|385","Alexander"],
["","East Carondelet","Village|499","St. Clair"],
["","East Dubuque","City|1,704","Jo Daviess"],
["","East Dundee","Village|2,860","Cook"],
["","East Galesburg","Village|8,12","Knox"],
["","East Gillespie","Village|270","Macoupin"],
["","East Hazel Crest","Village|1,543","Cook"],
["","East Moline","City|21,302","Rock Island"],
["","East Peoria","City|23,402","Tazewell"],
["","East St. Louis","City|27,006","St. Clair"],
["","Easton","Village|321","Mason"],
["","Eddyville","Village|101","Pope"],
["","Edgewood","Village|440","Effingham"],
["","Edinburg","Village|1,078","Christian"],
["","Edwardsville","City|24,293","Madison"],
["","Effingham","City|12,328","Effingham"],
["","El Dara","Village|78","Pike"],
["","El Paso","City|2,810","McLean"],
["","Elburn","Village|5,602","Kane"],
["","Eldorado","City|4,122","Saline"],
["","Eldred","Village|201","Greene"],
["","Elgin","City|108,188","Cook"],
["","Elizabeth","Village|761","Jo Daviess"],
["","Elizabethtown","Village|299","Hardin"],
["","Elk Grove Village","Village|33,127","Cook"],
["","Elkhart","Village|405","Logan"],
["","Elkville","Village|928","Jackson"],
["","Elliott","Village|295","Ford"],
["","Ellis Grove","Village|363","Randolph"],
["","Ellisville","Village|96","Fulton"],
["","Ellsworth","Village|195","McLean"],
["","Elmhurst","City|44,121","Cook"],
["","Elmwood","City|2,097","Peoria"],
["","Elmwood Park","Village|24,883","Cook"],
["","Elsah","Village|673","Jersey"],
["","Elvaston","Village|165","Hancock"],
["","Elwood","Village|2,279","Will"],
["","Emden","Village|485","Logan"],
["","Emington","Village|117","Livingston"],
["","Energy","Village|1,146","Williamson"],
["","Enfield","Village|596","White"],
["","Equality","Village|595","Gallatin"],
["","Erie","Village|1,602","Whiteside"],
["","Essex","Village|802","Kankakee"],
["","Eureka","City|5,295","Woodford"],
["","Evanston","City|74,486","Cook"],
["","Evansville","Village|701","Randolph"],
["","Evergreen Park","Village|19,852","Cook"],
["","Ewing","Village|307","Franklin"],
["","Exeter","Village|65","Scott"],
["","Fairbury","City|3,757","Livingston"],
["","Fairfield","City|5,154","Wayne"],
["","Fairmont City","Village|2,635","St. Clair"],
["","Fairmount","Village|642","Vermilion"],
["","Fairview","Village|522","Fulton"],
["","Fairview Heights","City|17,078","St. Clair"],
["","Farina","Village|518","Fayette"],
["","Farmer City","City|2,037","DeWitt"],
["","Farmersville","Village|724","Montgomery"],
["","Farmington","City|2,448","Fulton"],
["","Fayetteville","Village|366","St. Clair"],
["","Ferris","Village|156","Hancock"],
["","Fidelity","Village|114","Jersey"],
["","Fieldon","Village|239","Jersey"],
["","Fillmore","Village|330","Montgomery"],
["","Findlay","Village|683","Shelby"],
["","Fisher","Village|1,881","Champaign"],
["","Fithian","Village|485","Vermilion"],
["","Flanagan","Village|1,110","Livingston"],
["","Flat Rock","Village|331","Crawford"],
["","Flora","City|5,070","Clay"],
["","Florence","Village|38","Pike"],
["","Flossmoor","Village|9,464","Cook"],
["","Foosland","Village|101","Champaign"],
["","Ford Heights","Village|2,763","Cook"],
["","Forest City","Village|246","Mason"],
["","Forest Park","Village|14,167","Cook"],
["","Forest View","Village|698","Cook"],
["","Forrest","Village|1,220","Livingston"],
["","Forreston","Village|1,446","Ogle"],
["","Forsyth","Village|3,490","Macon"],
["","Fox Lake","Village|10,579","Lake"],
["","Fox River Grove","Village|4,854","Lake"],
["","Frankfort","Village|17,782","Cook"],
["","Franklin","Village|610","Morgan"],
["","Franklin Grove","Village|1,021","Lee"],
["","Franklin Park","Village|18,333","Cook"],
["","Freeburg","Village|4,354","St. Clair"],
["","Freeman Spur","Village|287","Williamson"],
["","Freeport","City|25,638","Stephenson"],
["","Fulton","City|3,481","Whiteside"],
["","Fults","Village|26","Monroe"],
["","Galatia","Village|933","Saline"],
["","Galena","City|3,429","Jo Daviess"],
["","Galesburg","City|32,195","Knox"],
["","Galva","City|2,589","Henry"],
["","Gardner","Village|1,463","Grundy"],
["","Garrett","Village|162","Douglas"],
["","Gays","Village|281","Moultrie"],
["","Geneseo","City|6,586","Henry"],
["","Geneva","City|21,495","Kane"],
["","Genoa","City|5,193","DeKalb"],
["","Georgetown","City|3,474","Vermilion"],
["","German Valley","Village|463","Stephenson"],
["","Germantown","Village|1,269","Clinton"],
["","Germantown Hills","Village|3,438","Woodford"],
["","Gibson City","City|3,407","Ford"],
["","Gifford","Village|975","Champaign"],
["","Gilberts","Village|6,879","Kane"],
["","Gillespie","City|3,319","Macoupin"],
["","Gilman","City|1,814","Iroquois"],
["","Girard","City|2,103","Macoupin"],
["","Gladstone","Village|281","Henderson"],
["","Glasford","Village|1,022","Peoria"],
["","Glasgow","Village|141","Scott"],
["","Glen Carbon","Village|12,934","Madison"],
["","Glen Ellyn","Village|27,450","DuPage"],
["","Glencoe","Village|8,723","Cook"],
["","Glendale Heights","Village|34,208","DuPage"],
["","Glenview","Village|44,692","Cook"],
["","Glenwood","Village|8,969","Cook"],
["","Godfrey","Village|17,982","Madison"],
["","Godley","Village|601","Grundy"],
["","Golconda","City|668","Pope"],
["","Golden","Village|644","Adams"],
["","Golden Gate","Village|68","Wayne"],
["","Golf","Village|500","Cook"],
["","Good Hope","Village|396","McDonough"],
["","Goodfield","Village|860","Tazewell"],
["","Goreville","Village|1,049","Johnson"],
["","Gorham","Village|236","Jackson"],
["","Grafton","City|674","Jersey"],
["","Grand Tower","City|605","Jackson"],
["","Grand Ridge","Village|560","LaSalle"],
["","Grandview","Village|1,441","Sangamon"],
["","Granite City","City|29,849","Madison"],
["","Grant Park","Village|1,331","Kankakee"],
["","Grantfork","Village|337","Madison"],
["","Granville","Village|1,427","Putnam"],
["","Grayslake","Village|20,957","Lake"],
["","Grayville","City|1,666","Edwards"],
["","Green Oaks","Village|3,866","Lake"],
["","Green Valley","Village|709","Tazewell"],
["","Greenfield","City|1,071","Greene"],
["","Greenup","Village|1,513","Cumberland"],
["","Greenview","Village|778","Menard"],
["","Greenville","City|7,000","Bond"],
["","Greenwood","Village|255","McHenry"],
["","Gridley","Village|1,432","McLean"],
["","Griggsville","City|1,226","Pike"],
["","Gulfport","Village|54","Henderson"],
["","Gurnee","Village|31,295","Lake"],
["","Hainesville","Village|3,597","Lake"],
["","Hamburg","Village|128","Calhoun"],
["","Hamel","Village|816","Madison"],
["","Hamilton","City|2,951","Hancock"],
["","Hammond","Village|509","Piatt"],
["","Hampshire","Village|5,563","Kane"],
["","Hampton","Village|1,863","Rock Island"],
["","Hanaford","Village|327","Franklin"],
["","Hanna City","Village|1,225","Peoria"],
["","Hanover","Village|844","Jo Daviess"],
["","Hanover Park","Village|39,973","Cook"],
["","Hardin","Village|967","Calhoun"],
["","Harmon","Village|120","Lee"],
["","Harrisburg","City|9,017","Saline"],
["","Harristown","Village|1,367","Macon"],
["","Hartford","Village|1,429","Madison"],
["","Hartsburg","Village|314","Logan"],
["","Harvard","City|9,447","McHenry"],
["","Harvel","Village|223","Montgomery"],
["","Harvey","City|25,282","Cook"],
["","Harwood Heights","Village|8,612","Cook"],
["","Havana","City|3,301","Mason"],
["","Hawthorn Woods","Village|7,663","Lake"],
["","Hazel Crest","Village|14,100","Cook"],
["","Hebron","Village|1,216","McHenry"],
["","Hecker","Village|481","Monroe"],
["","Henderson","Village|255","Knox"],
["","Hennepin","Village|757","Putnam"],
["","Henning","Village|251","Vermilion"],
["","Henry","City|2,464","Marshall"],
["","Herrick","Village|436","Shelby"],
["","Herrin","City|12,501","Williamson"],
["","Herscher","Village|1,591","Kankakee"],
["","Hettick","Village|181","Macoupin"],
["","Heyworth","Village|2,841","McLean"],
["","Hickory Hills","City|14,049","Cook"],
["","Hidalgo","Village|106","Jasper"],
["","Highland","City|9,919","Madison"],
["","Highland Park","City|29,763","Lake"],
["","Highwood","City|5,405","Lake"],
["","Hillcrest","Village|1,326","Ogle"],
["","Hillsboro","City|6,207","Montgomery"],
["","Hillsdale","Village|523","Rock Island"],
["","Hillside","Village|8,157","Cook"],
["","Hillview","Village|193","Greene"],
["","Hinckley","Village|2,070","DeKalb"],
["","Hindsboro","Village|313","Douglas"],
["","Hinsdale","Village|16,816","Cook"],
["","Hodgkins","Village|1,897","Cook"],
["","Hoffman","Village|508","Clinton"],
["","Hoffman Estates","Village|51,895","Cook"],
["","Holiday Hills","Village|610","McHenry"],
["","Hollowayville","Village|84","Bureau"],
["","Homer","Village|1,193","Champaign"],
["","Homer Glen","Village|24,220","Will"],
["","Hometown","City|4,349","Cook"],
["","Homewood","Village|19,323","Cook"],
["","Hoopeston","City|5,351","Vermilion"],
["","Hooppole","Village|204","Henry"],
["","Hopedale","Village|865","Tazewell"],
["","Hopewell","Village|410","Marshall"],
["","Hopkins Park","Village|603","Kankakee"],
["","Hoyleton","Village|531","Washington"],
["","Hudson","Village|1,838","McLean"],
["","Huey","Village|169","Clinton"],
["","Hull","Village|461","Pike"],
["","Humboldt","Village|437","Coles"],
["","Hume","Village|380","Edgar"],
["","Huntley","Village|24,291","Kane"],
["","Hurst","City|795","Williamson"],
["","Hutsonville","Village|554","Crawford"],
["","Illiopolis","Village|891","Sangamon"],
["","Ina","Village|2,338","Jefferson"],
["","Indian Creek","Village|462","Lake"],
["","Indian Head Park","Village|3,809","Cook"],
["","Indianola","Village|276","Vermilion"],
["","Industry","Village|478","McDonough"],
["","Inverness","Village|7,399","Cook"],
["","Iola","Village|141","Clay"],
["","Ipava","Village|470","Fulton"],
["","Iroquois","Village|154","Iroquois"],
["","Irving","Village|495","Montgomery"],
["","Irvington","Village|659","Washington"],
["","Irwin","Village|74","Kankakee"],
["","Island Lake","Village|8,080","Lake"],
["","Itasca","Village|8,649","DuPage"],
["","Iuka","Village|489","Marion"],
["","Ivesdale","Village|267","Champaign"],
["","Jacksonville","City|19,446","Morgan"],
["","Jeffersonville","Village|367","Wayne"],
["","Jeisyville","Village|107","Christian"],
["","Jerome","Village|1,656","Sangamon"],
["","Jerseyville","City|8,465","Jersey"],
["","Jewett","Village|223","Cumberland"],
["","Johnsburg","Village|6,337","McHenry"],
["","Johnston City","City|3,543","Williamson"],
["","Johnsonville","Village|77","Wayne"],
["","Joliet","City|147,433","Kendall"],
["","Jonesboro","City|1,821","Union"],
["","Joppa","Village|360","Massac"],
["","Joy","Village|417","Mercer"],
["","Junction","Village|129","Gallatin"],
["","Junction City","Village|482","Marion"],
["","Justice","Village|12,926","Cook"],
["","Kampsville","Village|328","Calhoun"],
["","Kane","Village|438","Greene"],
["","Kaneville","Village|484","Kane"],
["","Kangley","Village|251","LaSalle"],
["","Kankakee","City|27,537","Kankakee"],
["","Kansas","Village|787","Edgar"],
["","Kappa","Village|227","Woodford"],
["","Karnak","Village|499","Pulaski"],
["","Kaskaskia","Village|14","Randolph"],
["","Keenes","Village|83","Wayne"],
["","Keithsburg","City|609","Mercer"],
["","Keensburg","Village|210","Wabash"],
["","Kell","Village|219","Marion"],
["","Kempton","Village|231","Ford"],
["","Kenilworth","Village|2,513","Cook"],
["","Kenney","Village|326","DeWitt"],
["","Kewanee","City|12,916","Henry"],
["","Keyesport","Village|421","Bond"],
["","Kilbourne","Village|302","Mason"],
["","Kildeer","Village|3,968","Lake"],
["","Kincaid","Village|1,505","Christian"],
["","Kinderhook","Village|216","Pike"],
["","Kingston","Village|1,164","DeKalb"],
["","Kingston Mines","Village|302","Peoria"],
["","Kinmundy","City|796","Marion"],
["","Kinsman","Village|99","Grundy"],
["","Kirkland","Village|1,744","DeKalb"],
["","Kirkwood","Village|714","Warren"],
["","Knoxville","City|2,911","Knox"],
["","La Fayette","Village|223","Stark"],
["","La Grange","Village|15,550","Cook"],
["","La Grange Park","Village|13,579","Cook"],
["","La Harpe","City|1,235","Hancock"],
["","La Moille","Village|726","Bureau"],
["","La Prairie","Town","47","Adams"],
["","La Rose","Village|144","Marshall"],
["","LaSalle","City|9,609","LaSalle"],
["","Lacon","City|1,937","Marshall"],
["","Ladd","Village|1,295","Bureau"],
["","Lake Barrington","Village|4,973","Lake"],
["","Lake Bluff","Village|5,722","Lake"],
["","Lake in the Hills","Village|28,965","McHenry"],
["","Lake Ka-ho","Village|237","Macoupin"],
["","Lake Forest","City|19,375","Lake"],
["","Lake Villa","Village|8,741","Lake"],
["","Lake Zurich","Village|17,631","Lake"],
["","Lakemoor","Village|6,017","Lake"],
["","Lakewood","Village|3,811","McHenry"],
["","Lanark","City|1,457","Carroll"],
["","Lansing","Village|28,331","Cook"],
["","Latham","Village|380","Logan"],
["","Lawrenceville","City|4,348","Lawrence"],
["","Le Roy","City|3,560","McLean"],
["","Leaf River","Village|443","Ogle"],
["","Lebanon","City|4,418","St. Clair"],
["","Lee","Village|337","DeKalb"],
["","Leland","Village|977","LaSalle"],
["","Leland Grove","City|1,503","Sangamon"],
["","Lemont","Village|16,000","Cook"],
["","Lena","Village|2,912","Stephenson"],
["","Lenzburg","Village|521","St. Clair"],
["","Leonore","Village|130","LaSalle"],
["","Lerna","Village|286","Coles"],
["","Lewistown","City|2,384","Fulton"],
["","Lexington","City|2,060","McLean"],
["","Liberty","Village|516","Adams"],
["","Libertyville","Village|20,315","Lake"],
["","Lily Lake","Village|993","Kane"],
["","Lima","Village|163","Adams"],
["","Limestone","Village|1,598","Kankakee"],
["","Lincoln","City|14,504","Logan"],
["","Lincolnshire","Village|7,275","Lake"],
["","Lincolnwood","Village|12,590","Cook"],
["","Lindenhurst","Village|14,462","Lake"],
["","Lisbon","Village|285","Kendall"],
["","Lisle","Village|22,390","DuPage"],
["","Litchfield","City|6,939","Montgomery"],
["","Little York","Village|331","Warren"],
["","Littleton","Village|181","Schuyler"],
["","Liverpool","Village|129","Fulton"],
["","Livingston","Village|858","Madison"],
["","Loami","Village|745","Sangamon"],
["","Lockport","City|24,839","Will"],
["","Loda","Village|407","Iroquois"],
["","Lomax","Village|454","Henderson"],
["","Lombard","Village|43,395","DuPage"],
["","London Mills","Village|392","Fulton"],
["","Long Creek","Village|1,328","Macon"],
["","Long Grove","Village|8,043","Lake"],
["","Long Point","Village|226","Livingston"],
["","Longview","Village|153","Champaign"],
["","Loraine","Village|313","Adams"],
["","Lostant","Village|498","LaSalle"],
["","Louisville","Village|1,139","Clay"],
["","Loves Park","City|23,996","Boone"],
["","Lovington","Village|1,130","Moultrie"],
["","Ludlow","Village|371","Champaign"],
["","Lyndon","Village|648","Whiteside"],
["","Lynnville","Village|117","Morgan"],
["","Lynwood","Village|9,007","Cook"],
["","Lyons","Village|10,729","Cook"],
["","Macedonia","Village|63","Franklin"],
["","Machesney Park","Village|23,499","Winnebago"],
["","Mackinaw","Village|1,950","Tazewell"],
["","Macomb","City|19,288","McDonough"],
["","Macon","City|1,138","Macon"],
["","Madison","City|3,891","Madison"],
["","Maeystown","Village|157","Monroe"],
["","Magnolia","Village|260","Putnam"],
["","Mahomet","Village|7,258","Champaign"],
["","Makanda","Village|561","Jackson"],
["","Malden","Village|362","Bureau"],
["","Malta","Village|1,164","DeKalb"],
["","Manchester","Village|292","Scott"],
["","Manhattan","Village|7,051","Will"],
["","Manito","Village|1,642","Mason"],
["","Manlius","Village|359","Bureau"],
["","Mansfield","Village|906","Piatt"],
["","Manteno","Village|9,204","Kankakee"],
["","Maple Park","Village|1,310","Kane"],
["","Mapleton","Village|270","Peoria"],
["","Maquon","Village|284","Knox"],
["","Marengo","City|7,648","McHenry"],
["","Marietta","Village|112","Fulton"],
["","Marine","Village|960","Madison"],
["","Marion","City|17,193","Williamson"],
["","Marissa","Village|1,979","St. Clair"],
["","Mark","Village|555","Putnam"],
["","Markham","City|12,508","Cook"],
["","Maroa","City|1,801","Macon"],
["","Marquette Heights","City|2,824","Tazewell"],
["","Marseilles","City|5,094","LaSalle"],
["","Marshall","City|3,933","Clark"],
["","Martinton","Village|381","Iroquois"],
["","Martinsville","City|1,167","Clark"],
["","Maryville","Village|7,487","Madison"],
["","Mascoutah","City|7,483","St. Clair"],
["","Mason","Town","345","Effingham"],
["","Mason City","City|2,343","Mason"],
["","Matherville","Village|723","Mercer"],
["","Matteson","Village|19,009","Cook"],
["","Mattoon","City|18,555","Coles"],
["","Maunie","Village|139","White"],
["","Maywood","Village|24,090","Cook"],
["","Mazon","Village|1,015","Grundy"],
["","McClure","Village|402","Alexander"],
["","McCook","Village|228","Cook"],
["","McCullom Lake","Village|1,049","McHenry"],
["","McHenry","City|26,992","McHenry"],
["","McLean","Village|830","McLean"],
["","McLeansboro","City|2,883","Hamilton"],
["","McNabb","Village|285","Putnam"],
["","Mechanicsburg","Village|590","Sangamon"],
["","Media","Village|107","Henderson"],
["","Medora","Village|419","Macoupin"],
["","Melrose Park","Village|25,411","Cook"],
["","Melvin","Village|452","Ford"],
["","Mendon","Village|953","Adams"],
["","Mendota","City|7,372","LaSalle"],
["","Menominee","Village|248","Jo Daviess"],
["","Meredosia","Village|1,044","Morgan"],
["","Merrionette Park","Village|1,900","Cook"],
["","Metamora","Village|3,636","Woodford"],
["","Metcalf","Village|189","Edgar"],
["","Metropolis","City|6,537","Massac"],
["","Mettawa","Village|547","Lake"],
["","Middletown","Village|324","Logan"],
["","Midlothian","Village|14,819","Cook"],
["","Milan","Village|5,099","Rock Island"],
["","Milford","Village|1,306","Iroquois"],
["","Mill Creek","Village|65","Union"],
["","Mill Shoals","Village|215","White"],
["","Millbrook","Village|335","Kendall"],
["","Milledgeville","Village|1,032","Carroll"],
["","Millington","Village|665","Kendall"],
["","Millstadt","Village|4,011","St. Clair"],
["","Milton","Village|271","Pike"],
["","Mineral","Village|237","Bureau"],
["","Minier","Village|1,252","Tazewell"],
["","Minonk","City|2,078","Woodford"],
["","Minooka","Village|10,924","Grundy"],
["","Modesto","Village|189","Macoupin"],
["","Mokena","Village|18,740","Will"],
["","Moline","City|43,483","Rock Island"],
["","Momence","City|3,310","Kankakee"],
["","Monee","Village|5,148","Will"],
["","Monmouth","City|9,444","Warren"],
["","Monroe Center","Village|471","Ogle"],
["","Montgomery","Village|18,438","Kane"],
["","Monticello","City|5,548","Piatt"],
["","Montrose","Village|201","Effingham"],
["","Morris","City|13,636","Grundy"],
["","Morrison","City|4,188","Whiteside"],
["","Morrisonville","Village|1,056","Christian"],
["","Morton","Village|16,267","Tazewell"],
["","Morton Grove","Village|23,270","Cook"],
["","Mound City","City|588","Pulaski"],
["","Mound Station","Village|122","Brown"],
["","Mounds","City|810","Pulaski"],
["","Mount Auburn","Village|480","Christian"],
["","Mount Carmel","City|7,284","Wabash"],
["","Mount Carroll","City|1,717","Carroll"],
["","Mount Clare","Village|278","Macoupin"],
["","Mount Erie","Village|88","Wayne"],
["","Mount Morris","Village|2,998","Ogle"],
["","Mount Olive","City|2,099","Macoupin"],
["","Mount Prospect","Village|54,167","Cook"],
["","Mount Pulaski","City|1,566","Logan"],
["","Mount Sterling","City|2,025","Brown"],
["","Mount Vernon","City|15,277","Jefferson"],
["","Mount Zion","Village|5,833","Macon"],
["","Moweaqua","Village|1,831","Shelby"],
["","Muddy","Village|68","Saline"],
["","Mulberry Grove","Village|634","Bond"],
["","Muncie","Village|146","Vermilion"],
["","Mundelein","Village|31,064","Lake"],
["","Murphysboro","City|7,970","Jackson"],
["","Murrayville","Village|587","Morgan"],
["","Naperville","City|141,853","DuPage"],
["","Naplate","Village|496","LaSalle"],
["","Naples","Town","130","Scott"],
["","Nashville","City|3,258","Washington"],
["","Nason","City|236","Jefferson"],
["","Nauvoo","City|1,149","Hancock"],
["","Nebo","Village|340","Pike"],
["","Nelson","Village|170","Lee"],
["","Neoga","City|1,636","Cumberland"],
["","Neponset","Village|473","Bureau"],
["","New Athens","Village|2,054","St. Clair"],
["","New Baden","Village|3,349","Clinton"],
["","New Bedford","Village|75","Bureau"],
["","New Berlin","Village|1,346","Sangamon"],
["","New Boston","City|683","Mercer"],
["","New Burnside","Village|211","Johnson"],
["","New Canton","Town","359","Pike"],
["","New Douglas","Village|319","Madison"],
["","New Grand Chain","Village|210","Pulaski"],
["","New Haven","Village|433","Gallatin"],
["","New Holland","Village|269","Logan"],
["","New Lenox","Village|24,394","Will"],
["","New Milford","Village|697","Winnebago"],
["","New Minden","Village|215","Washington"],
["","New Salem","Village|137","Pike"],
["","New Windsor","Village|748","Mercer"],
["","Newark","Village|992","Kendall"],
["","Newman","City|865","Douglas"],
["","Newton","City|2,849","Jasper"],
["","Niantic","Village|707","Macon"],
["","Niles","Village|29,803","Cook"],
["","Nilwood","Town","239","Macoupin"],
["","Noble","Village|677","Richland"],
["","Nokomis","City|2,256","Montgomery"],
["","Nora","Village|121","Jo Daviess"],
["","Normal","Town","52,497","McLean"],
["","Norridge","Village|14,572","Cook"],
["","Norris","Village|213","Fulton"],
["","Norris City","Village|1,275","White"],
["","North Aurora","Village|16,760","Kane"],
["","North Barrington","Village|3,047","Lake"],
["","North Chicago","City|32,574","Lake"],
["","North City","Village|608","Franklin"],
["","North Henderson","Village|187","Mercer"],
["","North Pekin","Village|1,573","Tazewell"],
["","North Riverside","Village|6,672","Cook"],
["","North Utica","Village|1,352","LaSalle"],
["","Northbrook","Village|33,170","Cook"],
["","Northfield","Village|5,420","Cook"],
["","Northlake","City|12,323","Cook"],
["","Norwood","Village|478","Peoria"],
["","O'Fallon","City|28,281","St. Clair"],
["","Oak Brook","Village|7,883","Cook"],
["","Oak Grove","Village|396","Rock Island"],
["","Oak Forest","City|27,962","Cook"],
["","Oak Lawn","Village|56,690","Cook"],
["","Oak Park","Village|51,878","Cook"],
["","Oakbrook Terrace","City|2,134","DuPage"],
["","Oakdale","Village|221","Washington"],
["","Oakford","Village|286","Menard"],
["","Oakland","City|880","Coles"],
["","Oakwood","Village|1,595","Vermilion"],
["","Oakwood Hills","Village|2,083","McHenry"],
["","Oblong","Village|1,466","Crawford"],
["","Oconee","Village|180","Shelby"],
["","Odell","Village|1,046","Livingston"],
["","Odin","Village|1,076","Marion"],
["","Ogden","Village|810","Champaign"],
["","Oglesby","City|3,791","LaSalle"],
["","Ohio","Village|513","Bureau"],
["","Ohlman","Village|135","Montgomery"],
["","Okawville","Village|1,434","Washington"],
["","Old Mill Creek","Village|178","Lake"],
["","Old Ripley","Village|108","Bond"],
["","Old Shawneetown","Village|193","Gallatin"],
["","Olmsted","Village|333","Pulaski"],
["","Olney","City|9,115","Richland"],
["","Olympia Fields","Village|4,988","Cook"],
["","Omaha","Village|266","Gallatin"],
["","Onarga","Village|1,368","Iroquois"],
["","Oneida","City|700","Knox"],
["","Oquawka","Village|1,371","Henderson"],
["","Orangeville","Village|793","Stephenson"],
["","Oreana","Village|875","Macon"],
["","Oregon","City|3,721","Ogle"],
["","Orient","City|358","Franklin"],
["","Orion","Village|1,861","Henry"],
["","Orland Hills","Village|7,149","Cook"],
["","Orland Park","Village|56,767","Cook"],
["","Oswego","Village|30,355","Kendall"],
["","Ottawa","City|18,768","LaSalle"],
["","Otterville","Town","126","Jersey"],
["","Owaneco","Village|239","Christian"],
["","Palatine","Village|68,557","Cook"],
["","Palestine","Town","1,369","Crawford"],
["","Palmer","Village|229","Christian"],
["","Palmyra","Village|698","Macoupin"],
["","Palos Heights","City|12,515","Cook"],
["","Palos Hills","City|17,484","Cook"],
["","Palos Park","Village|4,847","Cook"],
["","Pana","City|5,847","Christian"],
["","Panama","Village|343","Bond"],
["","Panola","Village|45","Woodford"],
["","Papineau","Village|171","Iroquois"],
["","Paris","City|8,837","Edgar"],
["","Park City","City|7,570","Lake"],
["","Park Forest","Village|21,975","Cook"],
["","Park Ridge","City|37,480","Cook"],
["","Parkersburg","Village|199","Richland"],
["","Patoka","Village|584","Marion"],
["","Paw Paw","Village|870","Lee"],
["","Pawnee","Village|2,739","Sangamon"],
["","Paxton","City|4,473","Ford"],
["","Payson","Village|1,026","Adams"],
["","Pearl","Village|138","Pike"],
["","Pearl City","Village|838","Stephenson"],
["","Pecatonica","Village|2,195","Winnebago"],
["","Pekin","City|34,094","Tazewell"],
["","Peoria","City|115,007","Peoria"],
["","Peoria Heights","Village|6,156","Peoria"],
["","Peotone","Village|4,142","Will"],
["","Percy","Village|970","Randolph"],
["","Perry","Village|397","Pike"],
["","Peru","City|10,295","LaSalle"],
["","Pesotum","Village|551","Champaign"],
["","Petersburg","City|2,260","Menard"],
["","Phillipstown","Village|44","White"],
["","Philo","Village|1,466","Champaign"],
["","Phoenix","Village|1,964","Cook"],
["","Pierron","Village|600","Bond"],
["","Pinckneyville","City|5,648","Perry"],
["","Pingree Grove","Village|4,532","Kane"],
["","Piper City","Village|826","Ford"],
["","Pittsburg","Village|572","Williamson"],
["","Pittsfield","City|4,576","Pike"],
["","Plainfield","Village|39,581","Kendall"],
["","Plainville","Village|264","Adams"],
["","Plano","City|10,856","Kendall"],
["","Plattville","Village|242","Kendall"],
["","Pleasant Hill","Village|966","Pike"],
["","Pleasant Plains","Village|802","Sangamon"],
["","Plymouth","Village|505","Hancock"],
["","Pocahontas","Village|784","Bond"],
["","Polo","City|2,355","Ogle"],
["","Pontiac","City|11,931","Livingston"],
["","Pontoon Beach","Village|5,836","Madison"],
["","Pontoosuc","Village|146","Hancock"],
["","Poplar Grove","Village|5,023","Boone"],
["","Port Barrington","Village|1,517","Lake"],
["","Port Byron","Village|1,647","Rock Island"],
["","Posen","Village|5,987","Cook"],
["","Potomac","Village|750","Vermilion"],
["","Prairie City","Village|379","McDonough"],
["","Prairie du Rocher","Village|604","Randolph"],
["","Prairie Grove","Village|1,904","McHenry"],
["","Princeton","City|7,660","Bureau"],
["","Princeville","Village|1,738","Peoria"],
["","Prophetstown","City|2,080","Whiteside"],
["","Prospect Heights","City|16,256","Cook"],
["","Pulaski","Village|206","Pulaski"],
["","Quincy","City|40,633","Adams"],
["","Radom","Village|220","Washington"],
["","Raleigh","Village|350","Saline"],
["","Ramsey","Village|1,037","Fayette"],
["","Rankin","Village|561","Vermilion"],
["","Ransom","Village|384","LaSalle"],
["","Rantoul","Village|12,941","Champaign"],
["","Rapids City","Village|959","Rock Island"],
["","Raritan","Village|138","Henderson"],
["","Raymond","Village|1,006","Montgomery"],
["","Red Bud","City|3,698","Randolph"],
["","Reddick","Village|163","Kankakee"],
["","Redmon","Village|173","Edgar"],
["","Reynolds","Village|539","Rock Island"],
["","Richmond","Village|1,874","McHenry"],
["","Richton Park","Village|13,646","Cook"],
["","Richview","Village|253","Washington"],
["","Ridge Farm","Village|862","Vermilion"],
["","Ridgway","Village|869","Gallatin"],
["","Ridott","Village|164","Stephenson"],
["","Ringwood","Village|836","McHenry"],
["","Rio","Village|220","Knox"],
["","Ripley","Village|86","Brown"],
["","River Forest","Village|11,172","Cook"],
["","River Grove","Village|10,227","Cook"],
["","Riverdale","Village|13,549","Cook"],
["","Riverside","Village|8,875","Cook"],
["","Riverton","Village|3,455","Sangamon"],
["","Riverwoods","Village|3,660","Lake"],
["","Roanoke","Village|2,065","Woodford"],
["","Robbins","Village|5,337","Cook"],
["","Roberts","Village|362","Ford"],
["","Robinson","City|7,713","Crawford"],
["","Rochelle","City|9,574","Ogle"],
["","Rochester","Village|3,689","Sangamon"],
["","Rock City","Village|315","Stephenson"],
["","Rock Falls","City|9,266","Whiteside"],
["","Rock Island","City|39,018","Rock Island"],
["","Rockbridge","Village|169","Greene"],
["","Rockdale","Village|1,976","Will"],
["","Rockford","City|152,871","Winnebago"],
["","Rockton","Village|7,685","Winnebago"],
["","Rockwood","Village|42","Randolph"],
["","Rolling Meadows","City|24,099","Cook"],
["","Romeoville","Village|39,680","Will"],
["","Roodhouse","City|1,814","Greene"],
["","Roscoe","Village|10,785","Winnebago"],
["","Rose Hill","Village|80","Jasper"],
["","Roselle","Village|22,763","Cook"],
["","Rosemont","Village|4,202","Cook"],
["","Roseville","Village|989","Warren"],
["","Rosiclare","City|1,160","Hardin"],
["","Rossville","Village|1,331","Vermilion"],
["","Round Lake","Village|18,289","Lake"],
["","Round Lake Beach","Village|28,175","Lake"],
["","Round Lake Heights","Village|2,676","Lake"],
["","Round Lake Park","Village|7,505","Lake"],
["","Roxana","Village|1,542","Madison"],
["","Royal","Village|293","Champaign"],
["","Royal Lakes","Village|197","Macoupin"],
["","Royalton","Village|1,151","Franklin"],
["","Ruma","Village|317","Randolph"],
["","Rushville","City|3,192","Schuyler"],
["","Russellville","Village|94","Lawrence"],
["","Rutland","Village|318","LaSalle"],
["","Sadorus","Village|416","Champaign"],
["","Sailor Springs","Village|95","Clay"],
["","St. Anne","Village|1,257","Kankakee"],
["","St. Augustine","Village|120","Knox"],
["","St. Charles","City|32,974","DuPage"],
["","St. David","Village|589","Fulton"],
["","St. Elmo","City|1,426","Fayette"],
["","St. Francisville","City|697","Lawrence"],
["","St. Jacob","Village|1,098","Madison"],
["","St. Johns","Village|219","Perry"],
["","St. Joseph","Village|3,967","Champaign"],
["","St. Libory","Village|615","St. Clair"],
["","St. Peter","Village|359","Fayette"],
["","Ste. Marie","Village|244","Jasper"],
["","Salem","City|7,485","Marion"],
["","Sammons Point","Village|279","Kankakee"],
["","San Jose","Village|642","Logan"],
["","Sandoval","Village|1,274","Marion"],
["","Sandwich","City|7,421","DeKalb"],
["","Sauget","Village|159","St. Clair"],
["","Sauk Village","Village|10,506","Cook"],
["","Saunemin","Village|420","Livingston"],
["","Savanna","City|3,062","Carroll"],
["","Savoy","Village|7,280","Champaign"],
["","Sawyerville","Village|279","Macoupin"],
["","Saybrook","Village|693","McLean"],
["","Scales Mound","Village|376","Jo Daviess"],
["","Schaumburg","Village|74,227","Cook"],
["","Schiller Park","Village|11,793","Cook"],
["","Schram City","Village|586","Montgomery"],
["","Sciota","Village|61","McDonough"],
["","Scottville","Village|116","Macoupin"],
["","Seaton","Village|222","Mercer"],
["","Seatonville","Village|314","Bureau"],
["","Secor","Village|373","Woodford"],
["","Seneca","Village|2,371","Grundy"],
["","Sesser","City|1,931","Franklin"],
["","Shabbona","Village|925","DeKalb"],
["","Shannon","Village|757","Carroll"],
["","Shawneetown","City|1,239","Gallatin"],
["","Sheffield","Village|926","Bureau"],
["","Shelbyville","City|4,700","Shelby"],
["","Sheldon","Village|1,070","Iroquois"],
["","Sheridan","Village|2,137","LaSalle"],
["","Sherman","Village|4,148","Sangamon"],
["","Sherrard","Village|640","Mercer"],
["","Shiloh","Village|12,651","St. Clair"],
["","Shipman","Village|624","Macoupin"],
["","Shorewood","Village|15,615","Will"],
["","Shumway","Village|202","Effingham"],
["","Sibley","Village|272","Ford"],
["","Sidell","Village|617","Vermilion"],
["","Sidney","Village|1,233","Champaign"],
["","Sigel","Town","373","Shelby"],
["","Silvis","City|7,479","Rock Island"],
["","Simpson","Village|60","Johnson"],
["","Sims","Village|252","Wayne"],
["","Skokie","Village|64,784","Cook"],
["","Sleepy Hollow","Village|3,304","Kane"],
["","Smithboro","Village|177","Bond"],
["","Smithfield","Village|230","Fulton"],
["","Smithton","Village|3,963","St. Clair"],
["","Somonauk","Village|1,893","DeKalb"],
["","Sorento","Village|498","Bond"],
["","South Barrington","Village|4,565","Cook"],
["","South Beloit","City|7,892","Winnebago"],
["","South Chicago Heights","Village|4,139","Cook"],
["","South Elgin","Village|21,985","Kane"],
["","South Holland","Village|22,030","Cook"],
["","South Jacksonville","Village|3,331","Morgan"],
["","South Pekin","Village|1,146","Tazewell"],
["","South Roxana","Village|2,053","Madison"],
["","South Wilmington","Village|681","Grundy"],
["","Southern View","Village|1,642","Sangamon"],
["","Sparland","Village|406","Marshall"],
["","Sparta","City|4,302","Randolph"],
["","Spaulding","Village|873","Sangamon"],
["","Spillertown","Village|203","Williamson"],
["","Spring Bay","Village|452","Woodford"],
["","Spring Grove","Village|5,778","McHenry"],
["","Spring Valley","City|5,558","Bureau"],
["","Springerton","Village|110","White"],
["","Springfield","City|116,250","Sangamon"],
["","Standard","Village|220","Putnam"],
["","Standard City","Village|152","Macoupin"],
["","Stanford","Village|596","McLean"],
["","Staunton","City|5,139","Macoupin"],
["","Steeleville","Village|2,083","Randolph"],
["","Steger","Village|9,570","Cook"],
["","Sterling","City|15,370","Whiteside"],
["","Steward","Village|256","Lee"],
["","Stewardson","Village|734","Shelby"],
["","Stickney","Village|6,786","Cook"],
["","Stillman Valley","Village|1,120","Ogle"],
["","Stockton","Village|1,862","Jo Daviess"],
["","Stone Park","Village|4,946","Cook"],
["","Stonefort","Village|297","Saline"],
["","Stonington","Village|932","Christian"],
["","Stoy","Village|104","Crawford"],
["","Strasburg","Village|467","Shelby"],
["","Strawn","Village|100","Livingston"],
["","Streamwood","Village|39,858","Cook"],
["","Streator","City|13,710","LaSalle"],
["","Stronghurst","Village|883","Henderson"],
["","Sublette","Village|449","Lee"],
["","Sugar Grove","Village|8,997","Kane"],
["","Sullivan","City|4,440","Moultrie"],
["","Summerfield","Village|451","St. Clair"],
["","Summit","Village|11,054","Cook"],
["","Sumner","City|3,174","Lawrence"],
["","Sun River Terrace","Village|528","Kankakee"],
["","Swansea","Village|13,430","St. Clair"],
["","Sycamore","City|17,519","DeKalb"],
["","Symerton","Village|87","Will"],
["","Table Grove","Village|416","Fulton"],
["","Tallula","Village|488","Menard"],
["","Tamaroa","Village|638","Perry"],
["","Tamms","Village|632","Alexander"],
["","Tampico","Village|790","Whiteside"],
["","Taylor Springs","Village|690","Montgomery"],
["","Taylorville","City|11,246","Christian"],
["","Tennessee","Village|115","McDonough"],
["","Teutopolis","Village|1,530","Effingham"],
["","Thawville","Village|241","Iroquois"],
["","Thayer","Village|693","Sangamon"],
["","Thebes","Village|436","Alexander"],
["","Third Lake","Village|1,182","Lake"],
["","Thomasboro","Village|1,126","Champaign"],
["","Thompsonville","Village|543","Franklin"],
["","Thomson","Village|590","Carroll"],
["","Thornton","Village|2,338","Cook"],
["","Tilden","Village|934","Randolph"],
["","Tilton","Village|2,724","Vermilion"],
["","Timberlane","Village|934","Boone"],
["","Time","Village|23","Pike"],
["","Tinley Park","Village|56,703","Cook"],
["","Tiskilwa","Village|829","Bureau"],
["","Toluca","City|1,414","Marshall"],
["","Toledo","Village|1,238","Cumberland"],
["","Tolono","Village|3,447","Champaign"],
["","Toulon","City|1,292","Stark"],
["","Tonica","Village|768","LaSalle"],
["","Topeka","Town","76","Mason"],
["","Tovey","Village|512","Christian"],
["","Towanda","Village|480","McLean"],
["","Tower Hill","Village|611","Shelby"],
["","Tower Lakes","Village|1,283","Lake"],
["","Tremont","Village|2,236","Tazewell"],
["","Trenton","City|2,715","Clinton"],
["","Trout Valley","Village|537","McHenry"],
["","Troy","City|9,888","Madison"],
["","Troy Grove","Village|250","LaSalle"],
["","Tuscola","City|4,480","Douglas"],
["","Virginia","City|1,611","Cass"],
["","Ullin","Village|463","Pulaski"],
["","Union","Village|580","McHenry"],
["","Union Hill","Village|58","Kankakee"],
["","University Park","Village|7,129","Cook"],
["","Urbana","City|41,250","Champaign"],
["","Ursa","Village|626","Adams"],
["","Valier","Village|669","Franklin"],
["","Valley City","Village|13","Pike"],
["","Valmeyer","Village|1,263","Monroe"],
["","Vandalia","City|7,042","Fayette"],
["","Varna","Village|384","Marshall"],
["","Venedy","Village|138","Washington"],
["","Venice","City|1,890","Madison"],
["","Vergennes","Village|298","Jackson"],
["","Vermilion","Village|225","Edgar"],
["","Vermont","Village|667","Fulton"],
["","Vernon","Village|129","Marion"],
["","Vernon Hills","Village|25,113","Lake"],
["","Verona","Village|215","Grundy"],
["","Versailles","Village|478","Brown"],
["","Victoria","Village|316","Knox"],
["","Vienna","City|1,434","Johnson"],
["","Villa Grove","City|2,537","Douglas"],
["","Villa Park","Village|21,904","DuPage"],
["","Viola","Village|955","Mercer"],
["","Virden","City|3,425","Macoupin"],
["","Virgil","Village|329","Kane"],
["","Volo","Village|2,929","Lake"],
["","Wadsworth","Village|3,815","Lake"],
["","Waggoner","Village|266","Montgomery"],
["","Walnut","Village|1,416","Bureau"],
["","Walnut Hill","Village|108","Marion"],
["","Walshville","Village|64","Montgomery"],
["","Waltonville","Village|434","Jefferson"],
["","Wamac","City|1,185","Clinton"],
["","Wapella","Village|558","DeWitt"],
["","Warren","Village|1,428","Jo Daviess"],
["","Warrensburg","Village|1,210","Macon"],
["","Warrenville","City|13,140","DuPage"],
["","Warsaw","City|1,607","Hancock"],
["","Washburn","Village|1,155","Woodford"],
["","Washington","City|15,134","Tazewell"],
["","Washington Park","Village|4,196","St. Clair"],
["","Wataga","Village|843","Knox"],
["","Waterloo","City|9,811","Monroe"],
["","Waterman","Village|1,506","DeKalb"],
["","Watseka","City|5,255","Iroquois"],
["","Watson","Village|754","Effingham"],
["","Wauconda","Village|13,603","Lake"],
["","Waukegan","City|89,078","Lake"],
["","Waverly","City|1,307","Morgan"],
["","Wayne","Village|2,431","DuPage"],
["","Wayne City","Village|1,032","Wayne"],
["","Waynesville","Village|434","DeWitt"],
["","Weldon","Village|429","DeWitt"],
["","Wellington","Village|242","Iroquois"],
["","Wenona","City|1,056","LaSalle"],
["","Wenonah","Village|37","Montgomery"],
["","West Brooklyn","Village|142","Lee"],
["","West Chicago","City|27,086","DuPage"],
["","West City","Village|661","Franklin"],
["","West Dundee","Village|7,331","Kane"],
["","West Frankfort","City|8,182","Franklin"],
["","West Peoria","City|4,458","Peoria"],
["","West Point","Village|178","Hancock"],
["","West Salem","Village|897","Edwards"],
["","Westchester","Village|16,718","Cook"],
["","Western Springs","Village|12,975","Cook"],
["","Westfield","Village|601","Clark"],
["","Westmont","Village|24,685","DuPage"],
["","Westville","Village|3,202","Vermilion"],
["","Wheeler","Village|147","Jasper"],
["","Wheaton","City|52,894","DuPage"],
["","Wheeling","Village|37,648","Cook"],
["","White City","Village|232","Macoupin"],
["","White Hall","City|2,520","Greene"],
["","Whiteash","Village|241","Williamson"],
["","Williamsfield","Village|578","Knox"],
["","Williamson","Village|230","Madison"],
["","Williamsville","Village|1,476","Sangamon"],
["","Willisville","Village|633","Perry"],
["","Willow Hill","Village|230","Jasper"],
["","Willow Springs","Village|5,524","Will"],
["","Willowbrook","Village|8,540","DuPage"],
["","Wilmette","Village|27,087","Cook"],
["","Wilmington","City|5,724","Will"],
["","Wilmington","Village|142","Greene"],
["","Wilsonville","Village|586","Macoupin"],
["","Winchester","City|1,593","Scott"],
["","Windsor","Village|748","Mercer"],
["","Windsor","City|1,187","Shelby"],
["","Winfield","Village|9,080","DuPage"],
["","Winnebago","Village|3,101","Winnebago"],
["","Winnetka","Village|12,187","Cook"],
["","Winslow","Village|338","Stephenson"],
["","Winthrop Harbor","Village|6,742","Lake"],
["","Witt","City|903","Montgomery"],
["","Wonder Lake","Village|4,026","McHenry"],
["","Wood Dale","City|13,770","DuPage"],
["","Wood River","City|10,657","Madison"],
["","Woodhull","Village|811","Henry"],
["","Woodland","Village|324","Iroquois"],
["","Woodlawn","Village|698","Jefferson"],
["","Woodridge","Village|32,971","DuPage"],
["","Woodson","Village|512","Morgan"],
["","Woodstock","City|24,770","McHenry"],
["","Worden","Village|1,044","Madison"],
["","Worth","Village|10,789","Cook"],
["","Wyanet","Village|991","Bureau"],
["","Wyoming","City|1,429","Stark"],
["","Xenia","Village|391","Clay"],
["","Yale","Village|86","Jasper"],
["","Yates City","Village|693","Knox"],
["","Yorkville","City|16,921","Kendall"],
["","Zeigler","City|1,801","Franklin"],
["","Zion","City|24,413","Lake"],
];